trigger:
  batch: true
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

pr:
  branches:
    include:
      - '*'

variables:
  BuildConfiguration: Release
  TestProjects: src/**/*.Test.csproj
  ArtifactName: AssetMan
  NugetFeed: 'a009aa0f-b984-4f75-9908-96c2ba08e2ec/32936a78-ced4-48b3-b7e3-3c17135dfe30' # oss feed
  Dotnet2Version: 2.x
  Dotnet3Version: 3.x
  Mono2Version: '6_0_0'
  Mono3Version: '6_4_0'
  NugetVersion: '5.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'

  NugetArtifactName: nupkg
  AndroidProject: src/**/*.Android.csproj
  IosProject: src/**/*.iOS.csproj

stages:
- stage: Build_nuget_package
  jobs:
  - job: Build_nuget_package
    timeoutInMinutes: 15
    pool:
      vmImage: windows-latest

    steps:
    - task: UseDotNet@2
      displayName: Use dotnet $(Dotnet3Version)
      inputs:
        packageType: sdk
        version: $(Dotnet3Version)

    - script: dotnet tool install -g nbgv
      displayName: Install nbgv tool

    - script: nbgv cloud
      displayName: Set version in cloud environment

    - pwsh: |
        ./ci/Build-NugetPackage.ps1 `
            -Configuration $(BuildConfiguration) `
            -OutputDirectory '$(Build.ArtifactStagingDirectory)'
      displayName: Pack nuget packages

    - publish: '$(Build.ArtifactStagingDirectory)'
      displayName: Publish nupkg as artifact
      artifact: $(NugetArtifactName)

- stage: Run_tests
  jobs:
  - job: Unit_test
    timeoutInMinutes: 15
    strategy:
      matrix:
        dotnet2:
          DotnetVersion: $(Dotnet2Version)
        dotnet3:
          DotnetVersion: $(Dotnet3Version)

    pool:
      vmImage: windows-latest

    steps:
    - task: UseDotNet@2
      displayName: Use dotnet $(DotnetVersion)
      inputs:
        packageType: sdk
        version: $(DotnetVersion)

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        arguments: --configuration $(BuildConfiguration)
        projects: $(TestProjects)

  - job: UI_test_Android
    timeoutInMinutes: 15
    strategy:
      matrix:
        dotnet2:
          DotnetVersion: $(Dotnet2Version)
          MonoVersion: $(Mono2Version)
        dotnet3:
          DotnetVersion: $(Dotnet3Version)
          MonoVersion: $(Mono3Version)

    pool:
      vmImage: macos-latest

    steps:
    - task: UseDotNet@2
      displayName: Use dotnet $(DotnetVersion)
      inputs:
        packageType: sdk
        version: $(Dotnet2Version)

    - bash: |
        SYMLINK=$(MonoVersion)

        sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $SYMLINK

        MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
        echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
        echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
        echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
      displayName: "Set Xamarin SDK version to $(MonoVersion)"

    - task: NuGetToolInstaller@0
      displayName: Install nuget $(NugetVersion)
      inputs:
        versionSpec: $(NugetVersion)

    - download: current
      displayName: Download nupkg artifact
      artifact: '$(NugetArtifactName)'

    - pwsh: ./ci/Rewrite-ToUseNugetPackage.ps1 -NupkgPath "$(Pipeline.Workspace)/$(NugetArtifactName)" -ProjectFile "$(AndroidProject)"
      displayName: Rewrite project file

    - pwsh: Get-ChildItem "$(AndroidProject)" |% { nuget restore $_ }
      displayName: Restore packages

    - task: XamarinAndroid@1
      displayName: Build Android app
      inputs:
        projectFile: $(AndroidProject)
        configuration: $(BuildConfiguration)
        createAppPackage: true
        msbuildVersionOption: 'latest'

  - job: UI_test_iOS
    timeoutInMinutes: 15
    strategy:
      matrix:
        dotnet2:
          DotnetVersion: $(Dotnet2Version)
          MonoVersion: $(Mono2Version)
        dotnet3:
          DotnetVersion: $(Dotnet3Version)
          MonoVersion: $(Mono3Version)

    pool:
      vmImage: macos-latest

    steps:
    - task: UseDotNet@2
      displayName: Use dotnet $(DotnetVersion)
      inputs:
        packageType: sdk
        version: $(Dotnet2Version)

    - bash: |
        SYMLINK=$(MonoVersion)

        sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $SYMLINK

        MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
        echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
        echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
        echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
      displayName: "Set Xamarin SDK version to $(MonoVersion)"

    - task: NuGetToolInstaller@0
      displayName: Install nuget $(NugetVersion)
      inputs:
        versionSpec: $(NugetVersion)

    - download: current
      displayName: Download nupkg artifact
      artifact: '$(NugetArtifactName)'

    - pwsh: ./ci/Rewrite-ToUseNugetPackage.ps1 -NupkgPath "$(Pipeline.Workspace)/$(NugetArtifactName)" -ProjectFile "$(IosProject)"
      displayName: Rewrite project file

    - pwsh: Get-ChildItem "$(IosProject)" |% { nuget restore $_ }
      displayName: Restore packages

    - task: XamariniOS@2
      displayName: Build iOS app
      inputs:
        solutionFile: $(IosProject)
        configuration: 'Release'
        buildForSimulator: false
        packageApp: true
        signingIdentity: $(APPLE_CERTIFICATE_SIGNING_IDENTITY)
        signingProvisioningProfileID: $(APPLE_PROV_PROFILE_UUID)


- stage: Build_and_Publish_nuget_package
  jobs:
  - job: Build_and_Publish_nuget_package
    timeoutInMinutes: 15
    pool:
      vmImage: windows-latest

    steps:
    - task: NuGetToolInstaller@0
      displayName: Install nuget $(NugetVersion)
      inputs:
        versionSpec: $(NugetVersion)

    - download: current
      displayName: Download nupkg artifact
      artifact: '$(NugetArtifactName)'

    - task: NuGetCommand@2
      displayName: Push nuget packages
      inputs:
        command: 'push'
        feedsToUse: 'select'
        packagesToPush: '$(Pipeline.Workspace)/$(NugetArtifactName)/**/*.nupkg;!$(Pipeline.Workspace)/$(NugetArtifactName)/**/*.symbols.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: $(NugetFeed)
        versioningScheme: 'off'

    - task: NuGetCommand@2
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
      inputs:
        command: 'push'
        packagesToPush: '$(Pipeline.Workspace)/$(NugetArtifactName)/**/*.nupkg;!$(Pipeline.Workspace)/$(NugetArtifactName)/**/*.symbols.nupkg'
        nuGetFeedType: 'external'
        publishFeedCredentials: 'nuget - AssetMan* packages'

    - task: PublishSymbols@2
      inputs:
        SearchPattern: '**/bin/**/*.pdb'
        SymbolServerType: 'TeamServices'

    - task: PublishPipelineArtifact@0
      displayName: Publish artifacts
      inputs:
        artifactName: $(ArtifactName)
        targetPath: '$(Build.ArtifactStagingDirectory)'
